### ISSUE TITLE
Where is the code for the toolbox module?

### ISSUE THREAD

**Issue by Beliavsky** [aledinola/ToolboxFortran#1]
The file mod_numerical.f90 has many lines such as

`use toolbox, only: sort`

Where is the code for this module?

**Comment by aledinola** [comment]
Hi, a few programs use the sort subroutine in Fehr and Kindermann's toolbox which is publicly available here: [](https://github.com/fabiankindermann/ce-fortran/blob/main/installation/toolbox/toolbox.f90)
I added an explanation in the README

**Comment by aledinola** [comment]
https://github.com/fabiankindermann/ce-fortran/blob/main/installation/toolbox/toolbox.f90

**Comment by Beliavsky** [comment]
Thanks.
